categories = {
    "Wealthsimple": [
        "Wealthsimple"
    ],
    "Alcohol": [
        "LCBO RAO",
        "LCBO/RAO",
        "PURE BREW"
    ],
    "Groceries": [
        "68044 MACS CONV. STORES MANOTICK",
        "ADONIS",
        "BULK BARN",
        "CANADIAN TIRE",
        "CHAP CHAP SNACKS Ottawa",
        "DUNKIN",
        "FARM BOY",
        "FLASHFOOD",
        "FOOD",
        "FOOD BASICS",
        "FRESH",
        "FRESHCO",
        "GEORGE S MEAT SHOP",
        "HALIBUT HOUSE",
        "LOBLAWS",
        "MARKET",
        "METRO",
        "NO FRILLS",
        "NSEYA S",
        "NSEYA'S",
        "REVOLUTIONN",
        "REXALL",
        "RHEMA S",
        "RHEMA#S AFRICAN & CA",
        "SOBEYS",
        "SUPERMARKET",
        "Shoppers Drug Mart",
        "T&T",
        "TooGoodT",
        "WAL MART",
        "WAL*MART",
        "WALMART",
        "WALMART.CA",
        "YIG"
    ],
    "Restaurants": [
        "-Marble Slab JONNY CANUCK'S",
        "A W",
        "A&W",
        "ALISSAR LEBANESE",
        "AZTEC",
        "BAKERY",
        "BARBURRITO",
        "BBQ",
        "BIG BONE BBQ",
        "BOSTON PIZZA",
        "BRIG",
        "BROADWAY",
        "BURGER",
        "BURGER KING",
        "Bagel",
        "CAFE",
        "CHAP CHAP SNACKS",
        "CHARTWELLS",
        "CHARTWELLS OTTAWAUUCU OTTAWA",
        "CHARTWELLS-OTTAWAUUCU-279",
        "CHICK FIL A",
        "CHICK-FIL-A",
        "CHUNGCHUN",
        "CHUNGCHUN ORLEANS",
        "COBS BREAD",
        "COCO FRESH TEA",
        "COFFEE AND BAR",
        "CORA",
        "Carleton Web",
        "Chatime",
        "DAIRY QUEEN",
        "DAOL",
        "DELICIOUS STEAKHOUSE",
        "DINER",
        "DIVISORIA RESTO",
        "DOORDASH",
        "DOUGHNUTS",
        "EAST SIDE MARIO",
        "EUREST",
        "FAIRMONT CHATEAU",
        "FAIRMONT CHATEAU LAURIE",
        "FAMOUS WOK",
        "FAT BASTARD BURRITO",
        "FPOS MR. PRETZELS ORLEA",
        "FRIES",
        "FRUIT",
        "GOOD GRAZES",
        "GOOOD TASTY OAKWOOD",
        "GOOOD&TASTY",
        "GYUBEE",
        "HARVEY",
        "HEY KITCHEN",
        "HILL BAKEHOUSE",
        "JACK ASTOR'S",
        "JOLLIBEE-",
        "JUICE DUDEZ",
        "KREME NIDO",
        "LITTLE CAESARS",
        "LS Maison ODDO",
        "LUNCHBOX",
        "MANDARIN",
        "MARY BROWN'S",
        "MAVERICK'S",
        "MCDONALD",
        "MCDONALD'S",
        "MCDONALDS",
        "MEET NOODLE",
        "MENCHIE",
        "MIKE DEAN'S",
        "MILKMAN",
        "MISS MOLLY",
        "MR PRETZELS",
        "MR. PRETZELS",
        "MUCHO BURRITO",
        "NICKY",
        "NICKYPOPEYES",
        "NOM NOM",
        "OSTERIA ITALIA",
        "PITA BELL KABAB",
        "PIZZA",
        "PIZZERIA",
        "POKE",
        "POPEYES",
        "PRESOTEA",
        "Pizza Pizza",
        "RA TD PLACE STDM",
        "RA TD PLACE STDM OTTAWA",
        "RA-TD PLACE",
        "ROYAL OAK",
        "SAVEURS EPICERIE",
        "SAVEURS EPICERIEUBER EATS",
        "SEE ME SPARKLEMOXIES",
        "SEVEN ELEVEN",
        "SHAKER",
        "SHANGHAI",
        "SHAWARMA PALACE",
        "SHOPPERS",
        "SKIPTHEDISHES",
        "SOUL STONE",
        "SP GOOD GRAZES",
        "SPICE WORLD",
        "SQ *PANCHO'S",
        "SQ *SEE ME SPARKLE",
        "SQ SEE ME SPARKLE",
        "SQ SEE ME SPARKLE OTTAWA",
        "ST LOUIS BAR GRILL",
        "ST. LOUIS BAR & GRILL",
        "STARBUCKS",
        "STORE OTTAWA",
        "STORE OTTAWA ON",
        "SUBS",
        "SUBWAY",
        "SUSHI",
        "SUSHI KAN",
        "Seoul Dog",
        "Store Ottawa, ON",
        "TABLE SODAM",
        "TABLE SODAM ",
        "TACO",
        "TEALIVE",
        "THE ALLEY",
        "THE GREAT CANADIAN PO",
        "TIGER ROOTS",
        "TIM HORTONS",
        "TST MARBLE SLAB CREAME",
        "TST-MARBLE SLAB CREAME",
        "WENDY",
        "Wild Wing",
        "pos purchase Fpos George'S Meat Shop  Ottaw"
    ],
    "Clothing": [
        "ADIDAS",
        "BOATHOUSE",
        "CHEMIN DE MODE",
        "CLAIRE FRANCE",
        "FAIRWEATHER",
        "FERICHM",
        "H&M",
        "HUDSON S BAY",
        "LEZE THE LABEL",
        "LIBRAIR UNVDOTTAWA 9    OTTAWA",
        "MICA S",
        "MICA'S",
        "OLD NAVY",
        "OVO",
        "PAYPAL LAURA ML",
        "SHEIN",
        "SPORT CHEK",
        "SPORTS",
        "Shoe Company",
        "THE GAP",
        "THREADS TAILORS",
        "Tip Top",
        "VALUE VILLAGE",
        "WINNERS HOMESENSE",
        "WINNERS/HOMESENSE",
        "ZARA"
    ],
    "Entertainment": [
        "401 GAMES",
        "AIRALO",
        "ARCHERY",
        "Anchor Night Club",
        "BOWLING",
        "CALYPSO",
        "CARTA",
        "CRYPTO ARENA MERCHANDI",
        "Canada Computers",
        "DISNEYPLUS",
        "DOLLYS",
        "DOOLY'S OTTAWA INC. OTTAWA ON",
        "EB *ALL FALLS DOWN FIL  TORONTO",
        "EB ALL FALLS DOWN",
        "ENTERTAIN ST",
        "EVENTBRITE",
        "Entertain St991",
        "FALCON RIDGE",
        "GAMES",
        "GAMESTOP",
        "GLOBAL E E COMME VANCOUVER",
        "GLOBAL-E CANADA E-COMME VANCOUVER",
        "GOLF",
        "HIPSTER LASERS",
        "LANDMARK",
        "MIRABEL S YUMMIES",
        "MIRABEL'S YUMMIES 001   OTTAWA",
        "Monkey Kart",
        "NORDIK",
        "PERFORMANCE TENNI",
        "PHD IN WAVES",
        "PLAYSTATION",
        "PUTTING EDGE",
        "RAKUTEN",
        "RED DRAGON",
        "SEATGEEK",
        "SMASH ROOM",
        "SP PERFORMANCE TENNI    OTTAWA",
        "SP TSX1",
        "STEAM",
        "STITTSVILLE SHOOTING IN STITTSVILLE",
        "SWIMPLY",
        "Sunrise Records",
        "TCGPLAYER",
        "TCGPLAYER.COM",
        "TICKETMASTER",
        "Teamlab Planets Tokyo",
        "Top Karting Hull",
        "VR ADVENTURES.ZONE",
        "VRADVENTURES.ZONE",
        "WEEB MANIA",
        "YOMJERSTUDIO",
        "YOMJERSTUDIO            OTTAWA"
    ],
    "Car Loan": [
        "BANK STREET MAZDA",
        "Loan Payment"
    ],
    "Car Maintenance": [
        "CAR WASH",
        "CARLING TIRE",
        "Caps Auto",
        "OIL CHANGERS"
    ],
    "Travel": [
        "AIRCANADA",
        "AIRBNB",
        "AIRLINES",
        "CAA NORTH",
        "Caltrain",
        "GUEST SERVICES OF",
        "HOPPER",
        "HOTEL PONTIAC",
        "JRC SHINKANSEN",
        "JRC SMART EX TOKYO",
        "KLOOK",
        "KLOOK TRAVEL TECH",
        "MEGADONQUIJOTE",
        "MOXY DWNTN LOS ANGEL",
        "RADICAL TOKYO",
        "SEVEN-ELEVEN",
        "TEAMLAB PLANETS",
        "THE HOXTON",
        "Travel",
        "Hopper"
    ],
    "Subscriptions": [
        "DISNEYPLUS",
        "MEMBERSHIP FEE INSTALLMENT",
        "NETFLIX"
    ],
    "Car Insurance": [
        "BELAIR",
        "BELAIR INS/ASS",
        "BELAIRDIRECT"
    ],
    "Online Shopping": [
        "AFROBLAST",
        "ALIPAY",
        "AMAZON",
        "AMZN",
        "APPLE",
        "GAMBIT",
        "HIVEMAPPER",
        "JEWELLERS",
        "KIDDIE KOBBLER",
        "LEGO",
        "MY USADDRESS",
        "SIMPLYMODBOX",
        "SNAPLII",
        "TOTALDRIVE",
        "ZEFITBLAD.COM"
    ],
    "Transportation": [
        "BUSBUD",
        "IMPARK",
        "Mto Tsd",
        "PARKING",
        "PPARK",
        "PRESTO",
        "QP ORLEANS",
        "Uber",
        "Ubr*",
        "Lyft"
    ],
    "Doctors/Dental/Vision": [
        "ACE OF SPADES",
        "APPLE'S CROWN",
        "CHILDREN S HOSPITAL",
        "CHU SAINTE JUSTINE",
        "CLEARVIEW",
        "Echo",
        "HUNTER CHIROPRACTIC",
        "KITS",
        "LASIK MD",
        "PHYSIO",
        "TENTH LINE PHARMACY"
    ],
    "Personal Care": [
        "BATH & BODY WORKS",
        "CLORE",
        "DRY CLEANER",
        "G G GOLDEN HAIR",
        "G&G GOLDEN HAIR",
        "Hera Beauty",
        "MONAT",
        "MONTEGO",
        "NANCY S NAILS AND LASHE",
        "NANCY'S NAILS AND LASHE",
        "SALON AND SPA",
        "TETIANA ZINCHENKO"
    ],
    "Gym": [
        "FIT4LESS",
        "OTTAWACITY",
        "SHOWCASE",
        "SP CROSSROPE",
        "ZEFITBLAD"
    ],
    "Home Goods": [
        "ACCENT DECOR",
        "ATOMY",
        "BEST BUY",
        "CANADIANTIRE",
        "CDN TIRE",
        "DOLLAR TREE",
        "Dollarama",
        "GIANT TIGER",
        "HUDSON'S BAY",
        "Kylescouter",
        "MICHAELS #3948 MICHAELS ORLEANS",
        "MICHAELS MICHAELS",
        "PANDABUY",
        "QP",
        "QUICK PICK",
        "SP BENTLEY",
        "THE HOME DEPOT",
        "WAL-MART"
    ],
    "Income": [
        "ACTING APPOINTMENT PAY",
        "Acting / Appointment Pay",
        "Basic Pay",
        "MAISON ACCUEIL SAGESSE",
        "PAYROLL DEPOSIT COUVENT MONT ST JOSEPH",
        "PAYROLL DEPOSIT SARSFIELD COLONIAL HOME",
        "SARSFIELD COLONIAL HOME",
        "payroll deposit Maison Accueil-Sagesse"
    ],
    "Gas": [
        "CIRCLEK",
        "ESSO",
        "FUEL",
        "GAS",
        "MAC EWEN",
        "MACEWEN",
        "MACS",
        "MOBIL",
        "MRGAS",
        "PETRO",
        "PETROCAN",
        "PIONEER",
        "SHELL",
        "ULTRAMAR"
    ],
    "Church": [
        "CALVARY CHURCH"
    ],
    "Education": [
        "OPTIONS",
        "R I S E ACADEMY",
        "R.I.S.E. ACADEMY",
        "The Aqua Life Swim Sch"
    ],
    "Miscellaneous Payment": [
        "ABM WITHDRAWAL",
        "AICAMERCHAN",
        "CREDIT MEMO SENIORS' DISCOUNT",
        "FEELON DESIGN SRL",
        "FPOS *NPO7W5D52R48KX",
        "NPO W D R KX",
        "NZ DQ KODYMD",
        "OPOS WU",
        "OPOS WU * 800-",
        "PAY PER USE ODP PLAN",
        "PAYPAL XIJOCTJ",
        "REFUNDED",
        "Returned Payment",
        "SENIORS DISCOUNT",
        "WU"
    ],
    "Miscellaneous Charges": [
        "BRIDGE",
        "Dishonoured Payment",
        "HOTEL PONTIAC",
        "IMPARK00110003U",
        "INDIGO PARK",
        "LIBRAIR UNVDOTTAWA",
        "LIBRAIR UNVDOTTAWA OTTAWA",
        "MONTHLY FEES",
        "NCC- VINCENT MASSEY PA",
        "NSF",
        "OPL BPO",
        "OVERDRAFT INTEREST",
        "OVERDRAFT PROTECT. FEE PAY-PER-USE ODP PLAN",
        "Opl/Bpo",
        "PARKING",
        "PARKSMART",
        "PAYBYPHONE",
        "POLICE",
        "PREMIUM",
        "Place D'orlans",
        "SERVICE CHARGE",
        "TOLL"
    ],
    "Investment": [
        "RRSP"
    ],
    "Loan": [
        "CRA (REVENUE)-2024 TAX RETURN",
        "CRA REVENUE TAX RETURN"
    ],
    "Credit Card": [
        "CREDIT CARD LOC PAY",
        "TRIANGLE MASTERCARD"
    ],
    "Insurance": [
        "INSURANCE COWAN",
        "INSURANCE SUN LIFE",
        "SUN LIFE",
        "SUN LIFE PERSONAL INSURANCE"
    ],
    "Home Maintenance": [
        "GROUPE VERTDURE"
    ],
    "Pharmacy": [
        "FPOS ST. MARY HEALTH CENTOTTAW",
        "JEAN COUTU",
        "ORLEANS MEDICAL CENTRE",
        "ST MARY HEALTH CENTOTTAW"
    ],
    "WITHDRAWAL": [
        "WITHDRAWAL"
    ],
    "DEPOSIT": [
        "DEPOSIT"
    ]
}