categories = {
    "Wealthsimple": [
        "Wealthsimple"
    ],
    "Alcohol": [
        "LCBO/RAO",
        "PURE BREW"
    ],
    "Groceries": [
        "68044 MACS CONV. STORES MANOTICK",
        "BULK BARN",
        "CANADIAN TIRE",
        "CHAP CHAP SNACKS Ottawa",
        "DUNKIN",
        "FARM BOY",
        "FLASHFOOD",
        "FOOD",
        "FOOD BASICS",
        "FRESH",
        "FRESHCO",
        "HALIBUT HOUSE",
        "LOBLAWS",
        "MARKET",
        "METRO",
        "NO FRILLS",
        "NSEYA'S",
        "REVOLUTIONN",
        "REXALL",
        "SOBEYS",
        "SUPERMARKET",
        "Shoppers Drug Mart",
        "T&T",
        "TooGoodT",
        "WAL*MART",
        "WALMART.CA",
        "YIG"
    ],
    "Restaurants": [
        "-Marble Slab JONNY CANUCK'S",
        "A&W",
        "AZTEC",
        "BAKERY",
        "BARBURRITO",
        "BBQ",
        "BIG BONE BBQ",
        "BOSTON PIZZA",
        "BRIG",
        "BROADWAY",
        "BURGER",
        "BURGER KING",
        "Bagel",
        "CAFE",
        "CHAP CHAP SNACKS",
        "CHARTWELLS-OTTAWAUUCU-279",
        "CHICK-FIL-A",
        "CHUNGCHUN ORLEANS",
        "COBS BREAD",
        "COCO FRESH TEA",
        "COFFEE AND BAR",
        "CORA",
        "Carleton Web",
        "Chatime",
        "DAIRY QUEEN",
        "DAOL",
        "DELICIOUS STEAKHOUSE",
        "DINER",
        "DIVISORIA RESTO",
        "DOORDASH",
        "DOUGHNUTS",
        "EAST SIDE MARIO",
        "FAIRMONT CHATEAU",
        "FAIRMONT CHATEAU LAURIE",
        "FAT BASTARD BURRITO",
        "FRIES",
        "FRUIT",
        "GOOOD&TASTY",
        "GYUBEE",
        "HARVEY",
        "HEY KITCHEN",
        "JACK ASTOR'S",
        "JOLLIBEE-",
        "JUICE DUDEZ",
        "KREME NIDO",
        "LITTLE CAESARS",
        "LS Maison ODDO",
        "LUNCHBOX",
        "MANDARIN",
        "MARY BROWN'S",
        "MAVERICK'S",
        "MCDONALD'S",
        "MCDONALDS",
        "MEET NOODLE",
        "MENCHIE",
        "MIKE DEAN'S",
        "MILKMAN",
        "MISS MOLLY",
        "MUCHO BURRITO",
        "NICKY",
        "NICKYPOPEYES",
        "NOM NOM",
        "PITA BELL KABAB",
        "PIZZA",
        "PIZZERIA",
        "POKE",
        "POPEYES",
        "PRESOTEA",
        "Pizza Pizza",
        "RA-TD PLACE",
        "ROYAL OAK",
        "SAVEURS EPICERIE",
        "SAVEURS EPICERIEUBER EATS",
        "SEE ME SPARKLEMOXIES",
        "SHAKER",
        "SHANGHAI",
        "SHAWARMA PALACE",
        "SHOPPERS",
        "SKIPTHEDISHES",
        "SOUL STONE",
        "SP GOOD GRAZES",
        "SQ *PANCHO'S",
        "SQ *SEE ME SPARKLE",
        "ST. LOUIS BAR & GRILL",
        "STARBUCKS",
        "STORE OTTAWA ON",
        "SUBS",
        "SUBWAY",
        "SUSHI",
        "SUSHI KAN",
        "Seoul Dog",
        "Store Ottawa, ON",
        "TABLE SODAM ",
        "TACO",
        "TEALIVE",
        "THE ALLEY",
        "THE GREAT CANADIAN PO",
        "TIGER ROOTS",
        "TIM HORTONS",
        "TST-MARBLE SLAB CREAME",
        "WENDY",
        "Wild Wing",
        "pos purchase Fpos George'S Meat Shop  Ottaw"
    ],
    "Clothing": [
        "ADIDAS",
        "BOATHOUSE",
        "FAIRWEATHER",
        "H&M",
        "LEZE THE LABEL",
        "LIBRAIR UNVDOTTAWA 9    OTTAWA",
        "OLD NAVY",
        "OVO",
        "SHEIN",
        "SPORT CHEK",
        "SPORTS",
        "Shoe Company",
        "THE GAP",
        "THREADS TAILORS",
        "Tip Top",
        "VALUE VILLAGE",
        "ZARA"
    ],
    "Entertainment": [
        "401 GAMES",
        "AIRALO",
        "ARCHERY",
        "Anchor Night Club",
        "BOWLING",
        "CALYPSO",
        "CARTA",
        "CRYPTO ARENA MERCHANDI",
        "Canada Computers",
        "DISNEYPLUS",
        "DOLLYS",
        "DOOLY'S OTTAWA INC. OTTAWA ON",
        "EB *ALL FALLS DOWN FIL  TORONTO",
        "EVENTBRITE",
        "Entertain St991",
        "FALCON RIDGE",
        "GAMES",
        "GAMESTOP",
        "GLOBAL-E CANADA E-COMME VANCOUVER",
        "GOLF",
        "HIPSTER LASERS",
        "LANDMARK",
        "MIRABEL'S YUMMIES 001   OTTAWA",
        "Monkey Kart",
        "NORDIK",
        "PHD IN WAVES",
        "PLAYSTATION",
        "PUTTING EDGE",
        "RAKUTEN",
        "RED DRAGON",
        "SEATGEEK",
        "SMASH ROOM",
        "SP PERFORMANCE TENNI    OTTAWA",
        "SP TSX1",
        "STEAM",
        "STITTSVILLE SHOOTING IN STITTSVILLE",
        "SWIMPLY",
        "Sunrise Records",
        "TCGPLAYER",
        "TCGPLAYER.COM",
        "TICKETMASTER",
        "Teamlab Planets Tokyo",
        "Top Karting Hull",
        "VR ADVENTURES.ZONE",
        "VRADVENTURES.ZONE",
        "WEEB MANIA",
        "YOMJERSTUDIO            OTTAWA"
    ],
    "Car Loan": [
        "BANK STREET MAZDA",
        "Loan Payment"
    ],
    "Car Maintenance": [
        "CAR WASH",
        "CARLING TIRE",
        "Caps Auto",
        "OIL CHANGERS"
    ],
    "Travel": [
        "AIRCANADA",
        "AIRBNB",
        "AIRLINES",
        "CAA NORTH",
        "Caltrain",
        "GUEST SERVICES OF",
        "HOPPER",
        "HOTEL PONTIAC",
        "JRC SHINKANSEN",
        "JRC SMART EX TOKYO",
        "KLOOK",
        "KLOOK TRAVEL TECH",
        "MEGADONQUIJOTE",
        "MOXY DWNTN LOS ANGEL",
        "RADICAL TOKYO",
        "SEVEN-ELEVEN",
        "TEAMLAB PLANETS",
        "THE HOXTON",
        "Travel",
        "Hopper"
    ],
    "Subscriptions": [
        "DISNEYPLUS",
        "MEMBERSHIP FEE INSTALLMENT",
        "NETFLIX"
    ],
    "Car Insurance": [
        "BELAIR",
        "BELAIR INS/ASS",
        "BELAIRDIRECT"
    ],
    "Online Shopping": [
        "AFROBLAST",
        "AMAZON",
        "AMZN",
        "APPLE",
        "HIVEMAPPER",
        "JEWELLERS",
        "LEGO",
        "MY USADDRESS",
        "SIMPLYMODBOX",
        "SNAPLII"
    ],
    "Transportation": [
        "BUSBUD",
        "IMPARK",
        "Mto Tsd",
        "PARKING",
        "PPARK",
        "PRESTO",
        "QP ORLEANS",
        "Uber",
        "Ubr*",
        "Lyft"
    ],
    "Doctors/Dental/Vision": [
        "ACE OF SPADES",
        "APPLE'S CROWN",
        "CLEARVIEW",
        "Echo",
        "HUNTER CHIROPRACTIC",
        "KITS",
        "LASIK MD",
        "PHYSIO",
        "TENTH LINE PHARMACY"
    ],
    "Personal Care": [
        "BATH & BODY WORKS",
        "CLORE",
        "MONAT",
        "MONTEGO",
        "NANCY'S NAILS AND LASHE"
    ],
    "Gym": [
        "FIT4LESS",
        "OTTAWACITY",
        "SHOWCASE",
        "SP CROSSROPE"
    ],
    "Home Goods": [
        "BEST BUY",
        "CANADIANTIRE",
        "CDN TIRE",
        "DOLLAR TREE",
        "Dollarama",
        "GIANT TIGER",
        "HUDSON'S BAY",
        "Kylescouter",
        "MICHAELS #3948 MICHAELS ORLEANS",
        "PANDABUY",
        "QUICK PICK",
        "WAL-MART"
    ],
    "Income": [
        "Acting / Appointment Pay",
        "Basic Pay",
        "payroll deposit Maison Accueil-Sagesse"
    ],
    "Gas": [
        "CIRCLEK",
        "ESSO",
        "FUEL",
        "GAS",
        "MAC EWEN",
        "MACEWEN",
        "MOBIL",
        "MRGAS",
        "PETRO",
        "PETROCAN",
        "PIONEER",
        "SHELL",
        "ULTRAMAR"
    ],
    "Church": [
        "CALVARY CHURCH"
    ],
    "Education": [
        "OPTIONS",
        "R.I.S.E. ACADEMY",
        "The Aqua Life Swim Sch"
    ],
    "Miscellaneous Payment": [
        "Returned Payment",
        "REFUNDED"
    ],
    "Miscellaneous Charges": [
        "Dishonoured Payment",
        "HOTEL PONTIAC",
        "IMPARK00110003U",
        "INDIGO PARK",
        "MONTHLY FEES",
        "NCC- VINCENT MASSEY PA",
        "NSF",
        "Opl/Bpo",
        "PARKING",
        "PARKSMART",
        "PAYBYPHONE",
        "PREMIUM",
        "Place D'orlans",
        "BRIDGE",
        "TOLL"
    ]
}