# Generated by Django 4.0.2 on 2022-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TransactonDescript', models.CharField(max_length=500)),
                ('Amount', models.IntegerField()),
                ('TransactonDate', models.DateField()),
                ('BankAction', models.CharField(max_length=1)),
            ],
        ),
    ]
