# Generated by Django 4.0.2 on 2022-03-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trans',
        ),
    ]
